# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    target-branch: "main"
    ignore:
      - dependency-name: "*" 
        update-types: ["version-update:semver-patch"]
    groups:
      nuget:
        applies-to: version-updates
        update-types: 
          - "major"
          - "minor"
          - "patch"
          
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Energy.App.Standalone" # Location of package manifests
    schedule:
      interval: "monthly"
    target-branch: "main"
    ignore:
      - dependency-name: "*" 
        update-types: ["version-update:semver-patch"]
    groups:
      npm:
        applies-to: version-updates
        update-types: 
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

    
