name: Resusable Unit Tests and Checks

on:
  workflow_call:
    inputs: 
      os:
        description: 'The OS to run the tests on'
        required: true
        type: string
        default: 'ubuntu-latest'
      frontendEnv:
        description: 'The frontend environment to run the tests on'
        required: true
        type: string
        default: 'staging'
      DotNetVersion:
        description: 'The .NET SDK version to use'
        required: true
        type: string
        default: '7.0.400'
      NodeVersion:
        description: 'The node version to use'
        required: true
        type: string
        default: '18.x'
      

env:
  DOTNET_VERSION: ${{inputs.DotNetVersion}} # The .NET SDK version to use
  NODE_VERSION: ${{inputs.NodeVersion}}  # The node version to use
      

jobs:
  unit-tests:
    name: Unit-Tests-and-Checks-${{inputs.os}}-${{inputs.frontendEnv}}
    runs-on: ${{ inputs.os }}
    permissions:
      checks: write
      contents: read
    defaults:
      run:
        shell: bash  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          lfs: false

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore and Build
        working-directory: ./
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Test .NET dependencies
        continue-on-error: true
        id: dotnet-tests
        run: |
          dotnet test Energy.Test --no-build --configuration Release --logger:"trx;LogFileName=TestResults.trx" --verbosity normal

      - name: Test Report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        if: success() || failure()
        with:
          name: Test Results ${{inputs.os}}
          path: Energy.Test/TestResults/TestResults.trx
          reporter: dotnet-trx
      
      - name: SetupNode
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./Energy.App.Standalone/package-lock.json
      
      - name: Install npm dependencies
        working-directory: ./Energy.App.Standalone
        run: npm ci
      
      - name: Test front-end dependencies
        continue-on-error: true
        id: frontend-tests
        working-directory: ./Energy.App.Standalone
        run: |
          npm test --environments=${{inputs.frontendEnv}}
      
      - name: Frontent Test Report 
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        if: success() || failure()
        with:
          name: Frontend Test Report ${{inputs.frontendEnv}}
          path: Energy.App.Standalone/testResults/clientDeploymentTestResults.xml
          reporter: java-junit
      
      - name: Report Results and Checks
        run: |
          echo "## Test Results for ${{ inputs.os }} - ${{inputs.frontendEnv}}" >> "$GITHIB_STEP_SUMMARY"
          echo "- dotnet v${{env.DOTNET_VERSION}}" >> "$GITHIB_STEP_SUMMARY"
          echo "- node v${{env.NODE_VERSION}}" >> "$GITHIB_STEP_SUMMARY"
          echo "### dotnet-tests result: ${{ steps.dotnet-tests.outcome }}" >> ""$GITHIB_STEP_SUMMARY"
          echo "### frontend-tests result: ${{ steps.frontend-tests.outcome }}" >> "$GITHIB_STEP_SUMMARY"

          if [[ "${{ steps.dotnet-tests.outcome }}" == "success" && "${{ steps.frontend-tests.outcome }}" == "success" ]]; then
            echo " - All tests passed" >> "$GITHIB_STEP_SUMMARY"
          else
            echo " - Failed tests" >> "$GITHIB_STEP_SUMMARY"
            exit 1
          fi

