name: Staging Build and Test

on:
  push:
    branches:
      - master
      - dev
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  DOTNET_VERSION: '7.0.400' # The .NET SDK version to use
      

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore and Build
        working-directory: ./
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Test .NET dependencies
        run: dotnet test Energy.Test --no-build --configuration Release --logger:"trx;LogFileName=TestResults.trx"

      - name: Test Report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        if: success() || failure()
        with:
          name: Test Results
          path: Energy.Test/TestResults/TestResults.trx
          reporter: dotnet-trx
  

